sonar.projectKey=marait123_gezamko-shop-backend
sonar.organization=marait123
sonar.projectName=Gezamko Shop Backend
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/venv/**,**/migrations/**,**/__pycache__/**,**/tests/**,**/staticfiles/**,**/media/**,**/logs/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

sonar.sourceEncoding=UTF-8
